[theme]
primaryColor = "#1f77b4"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#000000"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true
